version: '3.1'

services:
    reverseproxy:
        image: jwilder/nginx-proxy:latest
        container_name: my_reverseproxy
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        restart: always

    jenkins:
        depends_on:
            - reverseproxy
        image: jenkinsci/blueocean:1.10.1
        container_name: my_jenkins
        user: root
        volumes:
            - /opt/jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - VIRTUAL_HOST=jenkins.localhost 
            - VIRTUAL_PORT=8080
        restart: always
