version: '3.1'

services:
    reverseproxy:
        image: jwilder/nginx-proxy:latest
        container_name: my_reverseproxy
        ports:
            - 80:80
            - 443:443
        volumes:
            - /home/appuser/certs:/etc/nginx/certs
            - /var/run/docker.sock:/tmp/docker.sock:ro
        restart: always

    jenkins:
        depends_on:
            - reverseproxy
        image: my_jenkins
        build:
            context: ./jenkins
            dockerfile: Dockerfile
        container_name: my_jenkins
        user: root
        volumes:
            - /opt/jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - VIRTUAL_HOST=jenkins.sogeo.services
            - VIRTUAL_PORT=8080
        restart: always

    pdf4oereb:
        depends_on:
            - reverseproxy
        image: sogis/pdf4oereb-web-service:latest
        container_name: my_pdf4oereb
        expose:
            - "8888"
        environment:
            - VIRTUAL_HOST=pdf4oereb.sogeo.services
            - VIRTUAL_PORT=8888
            - SERVER_SERVLET_CONTEXT_PATH=/
        restart: always

    artifactory:
        depends_on:
            - reverseproxy
        image: docker.bintray.io/jfrog/artifactory-oss:6.6.5
        container_name: my_artifactory
        expose:
            - "8081"
        environment:
            - VIRTUAL_HOST=artifactory.sogeo.services
            - VIRTUAL_PORT=8081
        restart: always
